SET NAMES 'GBK';

CREATE DATABASE IF NOT EXISTS db_traver_price  CHARACTER SET  GBK;

USE db_traver_price;

DROP TABLE IF EXISTS t_air_ticket;

CREATE TABLE t_air_ticket (
    id INT(11) NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    ticket_num INT(11) NOT NULL DEFAULT 0 UNIQUE COMMENT '机票编号',
    ticket_info VARCHAR(20480) NOT NULL DEFAULT '' COMMENT '票价相关信息见表t_ticket_price',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期'
)ENGINE=INNODB, CHARACTER SET=GBK;

DROP TABLE IF EXISTS t_pick_service;
CREATE TABLE t_pick_service (
    id INT(11) NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    service_num INT(11) NOT NULL DEFAULT 0 UNIQUE COMMENT '地接服务产品编号',
    service_info VARCHAR(20480) NOT NULL DEFAULT '' COMMENT '地接服务信息',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期'
)ENGINE=INNODB, CHARACTER SET=GBK;

DROP TABLE IF EXISTS t_channel;
CREATE TABLE t_channel (
    id INT(11) NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    channel_name  VARCHAR(32) NOT NULL  DEFAULT '' UNIQUE COMMENT '渠道名称',
    channel_info VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '渠道信息',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期'
)ENGINE=INNODB, CHARACTER SET=GBK;

DROP TABLE IF EXISTS t_channel_relation;
CREATE TABLE t_channel_relation (
    id INT(11) NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    channel_name  VARCHAR(32) NOT NULL  DEFAULT '' COMMENT '渠道名称',
    shop_product_id INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联的商品id',
    channel_relation_info VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '渠道关联信息',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    UNIQUE INDEX channel_relation(channel_name, shop_product_id)
)ENGINE=INNODB, CHARACTER SET=GBK;

/*
CREATE TABLE t_air_ticket (
    id INT(11) NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    ticket_num INT(11) NOT NULL DEFAULT 0 UNIQUE COMMENT '机票编号',
    ticket_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '机票名称',
    ticket_days SMALLINT NOT NULL DEFAULT 0 COMMENT '往返天数',
    ticket_departure VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出发地',
    ticket_destination VARCHAR(255) NOT NULL DEFAULT '' COMMENT '目的地',
    ticket_price VARCHAR(20480) NOT NULL DEFAULT '' COMMENT '票价相关信息见表t_ticket_price',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期'
)ENGINE=INNODB, CHARACTER SET=GBK;
*/

/*
DROP TABLE IF EXISTS t_ticket_price;
CREATE TABLE t_ticket_price (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    ticket_num INT(11) NOT NULL DEFAULT 0 COMMENT '机票编号',
    ticket_departure_ym VARCHAR(255)  NULL DEFAULT '' COMMENT '出发年月',
    ticket_departure_day VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出发日（几号）',
    ticket_adult_price INT(11) NOT NULL DEFAULT 0 COMMENT '成人票价',
    ticket_child_price INT(11) NOT NULL DEFAULT 0 COMMENT '小孩票价',
    LASTTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期'
)ENGINE=INNODB, CHARACTER SET=GBK;
*/
